# config.yaml
model_list:
  - model_name: kimi-k2.5
    litellm_params:
      model: anthropic/kimi-for-coding
      api_key: sk-kimi-ns5ItGWwxAiTRpGb6UeK7sEH3V4ROEhyND3AhxNlCOOT0bHNysAWrRmpQzV4e0dB
      api_base: https://api.kimi.com/coding/

  - model_name: glm-4.7
    litellm_params:
      model: anthropic/glm-4.7
      api_key: 0f3cb4ead042483d804febd903f59ab4.DdI5tleodrc34ktX
      api_base: https://api.z.ai/api/anthropic

  - model_name: MiniMax-M2.1
    litellm_params:
      model: anthropic/MiniMax-M2.1
      api_key: sk-cp-VXrqtidSwDOnoRxSqr2j2NrilJb_06UYgYRZxMpvYBRjLpQJ8fLyhTgAtcuSu1gTSsQAcR4ZlqpSePJ7St94Fd2p8AfHYgerqGAnBsNX_0B-Qx9bRgeiK90
      api_base: https://api.minimax.io/anthropic

# general_settings:
#   master_key: sk-proxy-auth
